name: CI

on: push
jobs:
  build:
    name: Java ${{ matrix.java }}"
    strategy:
      fail-fast: false
      matrix:
        java: [11, 12, 13]
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: 'Build'
      run: cd java-compiled-versions && java Build.java
