name: java-compiled-versions

on: push
jobs:
  build:
    name: "Java 11"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: "Set up Java 11"
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'java --version'
      run: java --version
    - name: 'java Build.java (no release)'
      run: cd java-compiled-versions && java Build.java
    - name: 'java Build.java (11)'
      run: cd java-compiled-versions && java Build.java 11
    - name: 'java Build.java (10)'
      run: cd java-compiled-versions && java Build.java 10
    - name: 'java Build.java (9)'
      run: cd java-compiled-versions && java Build.java 9
