name: javadoc-link-non-modular

on: push
jobs:
  build:
    name: "Javadoc"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: "Set up Java 15"
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: 'java --version'
      run: java --version
    - name: 'java Build.java'
      run: cd javadoc-link-non-modular && java Build.java
